	
six_embed embed six_extra extra:
	gcc -o six_embed  sixmac.c   algorithm.c
	gcc -o embed      onemac.c   algorithm.c
	gcc -o six_extra  sixextra.c algorithm.c
	gcc -o extra      oneextra.c algorithm.c


clean:
	rm -rf *.d *.o six_embed embed six_extra extra

